[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/"
  to = "/provider-app/"
  status = 302

[functions."check-report-status"]
  schedule = "@daily"

[functions."check-mar-medication-alerts"]
  schedule = "@daily"
